### ISSUE TITLE
Bug: Section [container] has no property [new_scopes_behavior] in create.sh

### ISSUE THREAD

**Issue by seanlubbers1** [GoogleCloudPlatform/gke-cloud-sql-postgres-demo#23]
Running into issues with the ./create.sh command.

After running the command USER_PASSWORD=pword PG_ADMIN_CONSOLE_PASSWORD=pword ./create.sh dbadmin pgadmin

I'm met with the following error:

ERROR: (gcloud.config.set) Section [container] has no property [new_scopes_behavior].

Haven't been successful with any workarounds.

**Comment by chrislovecnm** [comment]
Did you resolve this?

**Comment by seanlubbers1** [comment]
Colleague figured it out—pm me at slubbers@google.com if you want some more info.
